SELECT ?d (COUNT(?d) as ?count)
WHERE {
    ?s  ?pe  ?ob .
    BIND(DATATYPE(?ob) as ?d)
    {
    #return me
    SELECT ?s (COUNT(?s) as ?count) 
    WHERE {
        ?s ?p ?o .
    }
    GROUP BY ?s
    ORDER BY DESC(?count)
    
    LIMIT 1
    }
}
Group by ?d